"use client";
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from "boneyard-js";
import { configureBoneyard } from "boneyard-js/react";

import _blog_index from "./blog-index.bones.json";
import _blog_post from "./blog-post.bones.json";
import _docs_page from "./docs-page.bones.json";
import _icons_page from "./icons-page.bones.json";
import _motion_page from "./motion-page.bones.json";
import _ui_page from "./ui-page.bones.json";

configureBoneyard({ animate: "solid" });

registerBones({
  "blog-index": _blog_index,
  "blog-post": _blog_post,
  "docs-page": _docs_page,
  "icons-page": _icons_page,
  "motion-page": _motion_page,
  "ui-page": _ui_page,
});
