/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.
import * as React from 'react';

export const index: Record<string, any> = {
  index: {
    name: 'index',
    description: '',
    type: 'registry:style',
    dependencies: [
      'tw-animate-css',
      'class-variance-authority',
      'lucide-react',
    ],
    devDependencies: undefined,
    registryDependencies: ['utils'],
    files: [],
    keywords: [],
    component: null,
    command: '@sora/index',
  },
  'hello-world': {
    name: 'hello-world',
    description:
      'Minimal test block that renders shadcn Button with “Hello World”.',
    type: 'registry:ui',
    dependencies: undefined,
    devDependencies: undefined,
    registryDependencies: undefined,
    files: [
      {
        path: 'registry/components/hello-world/index.tsx',
        type: 'registry:ui',
        target: 'components/sora/hello-world.tsx',
        content:
          "import { Button } from '@/components/ui/button';\n\nexport function HelloWorld() {\n  return <Button>Hello World</Button>;\n}",
      },
    ],
    keywords: [],
    component: (function () {
      const LazyComp = React.lazy(async () => {
        const mod = await import('@/registry/components/hello-world/index.tsx');
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === 'function' || typeof mod[key] === 'object',
          ) || 'hello-world';
        const Comp = mod.default || mod[exportName];
        if (mod.animations) {
          (LazyComp as any).animations = mod.animations;
        }
        return { default: Comp };
      });
      LazyComp.demoProps = {};
      return LazyComp;
    })(),
    command: '@sora/hello-world',
  },
  'demo-hello-world': {
    name: 'demo-hello-world',
    description: 'Demo for the Hello World test block.',
    type: 'registry:ui',
    dependencies: undefined,
    devDependencies: undefined,
    registryDependencies: ['@sora/hello-world'],
    files: [
      {
        path: 'registry/demo/components/hello-world/index.tsx',
        type: 'registry:ui',
        target: 'components/sora/demo/hello-world.tsx',
        content:
          "'use client';\n\nimport { HelloWorld } from '@/components/sora/hello-world';\n\nexport const HelloWorldDemo = () => {\n  return (\n    <div className=\"flex items-center justify-center p-8\">\n      <HelloWorld />\n    </div>\n  );\n};",
      },
    ],
    keywords: [],
    component: (function () {
      const LazyComp = React.lazy(async () => {
        const mod =
          await import('@/registry/demo/components/hello-world/index.tsx');
        const exportName =
          Object.keys(mod).find(
            (key) =>
              typeof mod[key] === 'function' || typeof mod[key] === 'object',
          ) || 'demo-hello-world';
        const Comp = mod.default || mod[exportName];
        if (mod.animations) {
          (LazyComp as any).animations = mod.animations;
        }
        return { default: Comp };
      });
      LazyComp.demoProps = {};
      return LazyComp;
    })(),
    command: '@sora/demo-hello-world',
  },
};
