/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.
import * as React from "react";

export const previewComponents: Record<string, any> = {
  "demo-accordion": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/disclosure/accordion/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-border-trail": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/border-trail/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-border-trail-loading": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/border-trail-loading/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-border-trail-textarea": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/border-trail-textarea/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-cursor-trail-reveal": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/cursor-trail-reveal/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-custom-cursor": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/custom-cursor/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-dock-nav": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/dock-nav/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-highlight": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/highlight/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-highlight-click": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/highlight-click/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-logo-carousel-swapper": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/logo-carousel-swapper/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-magnetic-cards": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/magnetic-cards/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-scroll-gallery": React.lazy(async () => {
    const mod = await import(
      "@/components/catalog/scroll-gallery-catalog-preview"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-draw-underline-link": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/draw-underline-link/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-text-effect": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/text-effect/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-text-morph": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/text-morph/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-text-morph-input": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/text-morph-input/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-text-reveal-box": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/text-reveal-box/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-text-reveal-mask": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/text-reveal-mask/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-text-roll": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/text-roll/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "hooks-use-auto-height": React.lazy(async () => {
    const mod = await import("@/registry/hooks/use-auto-height/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "hooks-use-prefers-reduced-motion": React.lazy(async () => {
    const mod = await import(
      "@/registry/hooks/use-prefers-reduced-motion/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "char-stagger-button": React.lazy(async () => {
    const mod = await import(
      "@/registry/primitives/buttons/char-stagger-button/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "section-cta": React.lazy(async () => {
    const mod = await import(
      "@/registry/primitives/buttons/section-cta/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  accordion: React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/disclosure/accordion/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "border-trail": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/border-trail/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "cursor-trail-reveal": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/cursor-trail-reveal/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "custom-cursor": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/custom-cursor/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "dock-nav": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/dock-nav/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  highlight: React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/highlight/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "logo-carousel-swapper": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/logo-carousel-swapper/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "magnetic-cards": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/magnetic-cards/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "pixelated-image-reveal": React.lazy(async () => {
    const mod = await import(
      "@/registry/primitives/effects/pixelated-image-reveal/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "scroll-gallery": React.lazy(async () => {
    const mod = await import(
      "@/components/catalog/scroll-gallery-catalog-preview"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "draw-underline-link": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/draw-underline-link/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "text-effect": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/text-effect/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "text-morph": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/text-morph/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "text-reveal-block": React.lazy(async () => {
    const mod = await import(
      "@/registry/primitives/texts/text-reveal-block/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "text-reveal-box": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/text-reveal-box/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "text-reveal-mask": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/text-reveal-mask/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "text-roll": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/text-roll/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "text-scramble": React.lazy(async () => {
    const mod = await import(
      "@/registry/primitives/texts/text-scramble/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "text-underline": React.lazy(async () => {
    const mod = await import(
      "@/registry/primitives/texts/text-underline/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "primitives-animate-slot": React.lazy(async () => {
    const mod = await import("@/registry/primitives/animate/slot/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "primitives-animate-tabs": React.lazy(async () => {
    const mod = await import("@/registry/primitives/animate/tabs/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "primitives-animate-tooltip": React.lazy(async () => {
    const mod = await import("@/registry/primitives/animate/tooltip/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "primitives-buttons-button": React.lazy(async () => {
    const mod = await import("@/registry/primitives/buttons/button/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "primitives-effects-auto-height": React.lazy(async () => {
    const mod = await import(
      "@/registry/primitives/effects/auto-height/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "primitives-radix-tabs": React.lazy(async () => {
    const mod = await import("@/registry/primitives/radix/tabs/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && /^[A-Z]/.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
};
