/** biome-ignore-all lint: Autogenerated file */
/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.
import * as React from "react";

const PASCAL_CASE_RE = /^[A-Z]/;

export const previewComponents: Record<string, any> = {
  "demo-particle-hover-button": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/buttons/particle-hover-button/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-accordion": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/disclosure/accordion/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-expandable-tabs": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/disclosure/expandable-tabs/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-inline-testimonials": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/disclosure/inline-testimonials/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-border-trail": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/border-trail/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-border-trail-loading": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/border-trail-loading/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-border-trail-textarea": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/border-trail-textarea/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-cursor-bubble": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/cursor-bubble/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-cursor-trail-reveal": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/cursor-trail-reveal/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-custom-cursor": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/custom-cursor/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-dock-nav": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/dock-nav/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-hero-carousel": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/hero-carousel/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-highlight": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/highlight/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-highlight-click": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/highlight-click/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-infinite-scrolling-images": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/infinite-scrolling-images/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-logo-carousel-swapper": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/logo-carousel-swapper/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-magnetic-cards": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/magnetic-cards/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-pixel-background": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/pixel-background/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-progressive-blur": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/progressive-blur/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-scroll-chapters": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/scroll-chapters/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-scroll-gallery": React.lazy(async () => {
    const mod = await import(
      "@/components/catalog/scroll-gallery-catalog-preview"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-skeleton": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/skeleton/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-skeleton-shimmer": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/skeleton-shimmer/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-skeleton-shimmer-basic": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/skeleton-shimmer-basic/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-sticky-scroll-cards": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/sticky-scroll-cards/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-tilt-card": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/tilt-card/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-tilt-card-image": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/tilt-card-image/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-video-player": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/video-player/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-dia-text-reveal": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/dia-text-reveal/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-fog-text-reveal": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/fog-text-reveal/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-number-flow": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/number-flow/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-text-cursor-loop": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/text-cursor-loop/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-text-effect": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/text-effect/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-text-loop": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/text-loop/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-text-morph": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/text-morph/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-text-morph-input": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/text-morph-input/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-text-reveal-box": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/text-reveal-box/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-text-reveal-mask": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/text-reveal-mask/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-text-roll": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/text-roll/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-typer": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/typer/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-base-accordion": React.lazy(async () => {
    const mod = await import("@/registry/demo/ui/base/accordion/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-base-accordion-bordered": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/ui/base/accordion-bordered/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-base-accordion-multiple": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/ui/base/accordion-multiple/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-base-accordion-separated": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/ui/base/accordion-separated/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-alert-dialog": React.lazy(async () => {
    const mod = await import("@/registry/demo/ui/base/alert-dialog/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-alert-dialog-small": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/ui/base/alert-dialog-small/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-button": React.lazy(async () => {
    const mod = await import("@/registry/demo/ui/base/button/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-button-loading": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/ui/base/button-loading/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-button-motion": React.lazy(async () => {
    const mod = await import("@/registry/demo/ui/base/button-motion/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-button-sizes": React.lazy(async () => {
    const mod = await import("@/registry/demo/ui/base/button-sizes/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-button-variants": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/ui/base/button-variants/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-button-with-icon": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/ui/base/button-with-icon/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-checkbox": React.lazy(async () => {
    const mod = await import("@/registry/demo/ui/base/checkbox/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-checkbox-card": React.lazy(async () => {
    const mod = await import("@/registry/demo/ui/base/checkbox-card/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-checkbox-indeterminate": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/ui/base/checkbox-indeterminate/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-checkbox-with-text": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/ui/base/checkbox-with-text/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-context-menu": React.lazy(async () => {
    const mod = await import("@/registry/demo/ui/base/context-menu/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-context-menu-file": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/ui/base/context-menu-file/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-dialog": React.lazy(async () => {
    const mod = await import("@/registry/demo/ui/base/dialog/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-dialog-scrollable": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/ui/base/dialog-scrollable/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-dialog-share": React.lazy(async () => {
    const mod = await import("@/registry/demo/ui/base/dialog-share/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-bottom-sheet": React.lazy(async () => {
    const mod = await import("@/registry/demo/ui/radix/bottom-sheet/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-radix-button": React.lazy(async () => {
    const mod = await import("@/registry/demo/ui/radix/button/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-radix-button-loading": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/ui/radix/button-loading/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-radix-button-motion": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/ui/radix/button-motion/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-radix-button-sizes": React.lazy(async () => {
    const mod = await import("@/registry/demo/ui/radix/button-sizes/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-radix-button-variants": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/ui/radix/button-variants/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-radix-button-with-icon": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/ui/radix/button-with-icon/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-radix-checkbox": React.lazy(async () => {
    const mod = await import("@/registry/demo/ui/radix/checkbox/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-radix-checkbox-card": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/ui/radix/checkbox-card/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-radix-checkbox-indeterminate": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/ui/radix/checkbox-indeterminate/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-radix-checkbox-with-text": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/ui/radix/checkbox-with-text/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-radix-dialog": React.lazy(async () => {
    const mod = await import("@/registry/demo/ui/radix/dialog/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-radix-dialog-scrollable": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/ui/radix/dialog-scrollable/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "demo-radix-dialog-share": React.lazy(async () => {
    const mod = await import("@/registry/demo/ui/radix/dialog-share/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "hooks-use-auto-height": React.lazy(async () => {
    const mod = await import("@/registry/hooks/use-auto-height/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "hooks-use-controlled-state": React.lazy(async () => {
    const mod = await import("@/registry/hooks/use-controlled-state/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "hooks-use-is-in-view": React.lazy(async () => {
    const mod = await import("@/registry/hooks/use-is-in-view/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "hooks-use-prefers-reduced-motion": React.lazy(async () => {
    const mod = await import(
      "@/registry/hooks/use-prefers-reduced-motion/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "icons-arrow-right": React.lazy(async () => {
    const mod = await import("@/registry/icons/arrow-right/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "icons-bell": React.lazy(async () => {
    const mod = await import("@/registry/icons/bell/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "icons-chevrons": React.lazy(async () => {
    const mod = await import("@/registry/icons/chevrons/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "icons-icon": React.lazy(async () => {
    const mod = await import("@/registry/icons/icon/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "lib-ease": React.lazy(async () => {
    const mod = await import("@/registry/lib/ease/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "lib-get-strict-context": React.lazy(async () => {
    const mod = await import("@/registry/lib/get-strict-context/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "lib-scroll-trigger-utils": React.lazy(async () => {
    const mod = await import("@/registry/lib/scroll-trigger-utils/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "primitives-animate-slot": React.lazy(async () => {
    const mod = await import("@/registry/primitives/animate/slot/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "particle-hover-button": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/buttons/particle-hover-button/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "sliding-chip-button": React.lazy(async () => {
    const mod = await import(
      "@/registry/primitives/buttons/sliding-chip-button/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "stagger-button": React.lazy(async () => {
    const mod = await import(
      "@/registry/primitives/buttons/stagger-button/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  accordion: React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/disclosure/accordion/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "expandable-tabs": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/disclosure/expandable-tabs/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "inline-testimonials": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/disclosure/inline-testimonials/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "border-trail": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/border-trail/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "cursor-bubble": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/cursor-bubble/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "cursor-trail-reveal": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/cursor-trail-reveal/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "custom-cursor": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/custom-cursor/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "dock-nav": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/dock-nav/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "hero-carousel": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/hero-carousel/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  highlight: React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/highlight/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "infinite-scrolling-images": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/infinite-scrolling-images/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "logo-carousel-swapper": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/logo-carousel-swapper/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "magnetic-cards": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/magnetic-cards/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "pixel-background": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/pixel-background/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "pixel-image-loader": React.lazy(async () => {
    const mod = await import(
      "@/registry/primitives/effects/pixel-image-loader/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "pixelated-image-reveal": React.lazy(async () => {
    const mod = await import(
      "@/registry/primitives/effects/pixelated-image-reveal/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "progressive-blur": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/progressive-blur/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "scroll-chapters": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/scroll-chapters/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "scroll-gallery": React.lazy(async () => {
    const mod = await import(
      "@/components/catalog/scroll-gallery-catalog-preview"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  skeleton: React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/skeleton/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "skeleton-shimmer": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/skeleton-shimmer/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "sticky-scroll-cards": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/sticky-scroll-cards/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "tilt-card": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/tilt-card/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "video-player": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/effects/video-player/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "dia-text-reveal": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/dia-text-reveal/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "draw-underline-link": React.lazy(async () => {
    const mod = await import(
      "@/registry/primitives/texts/draw-underline-link/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "fog-text-reveal": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/fog-text-reveal/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "number-flow": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/number-flow/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "rolling-text": React.lazy(async () => {
    const mod = await import(
      "@/registry/primitives/texts/rolling-text/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "text-cursor-loop": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/text-cursor-loop/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "text-effect": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/text-effect/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "text-loop": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/text-loop/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "text-morph": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/text-morph/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "text-reveal-block": React.lazy(async () => {
    const mod = await import(
      "@/registry/primitives/texts/text-reveal-block/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "text-reveal-box": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/text-reveal-box/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "text-reveal-mask": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/text-reveal-mask/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "text-roll": React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/text-roll/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "text-scramble": React.lazy(async () => {
    const mod = await import(
      "@/registry/primitives/texts/text-scramble/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "text-underline": React.lazy(async () => {
    const mod = await import(
      "@/registry/primitives/texts/text-underline/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  typer: React.lazy(async () => {
    const mod = await import(
      "@/registry/demo/primitives/texts/typer/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "base-accordion": React.lazy(async () => {
    const mod = await import("@/registry/demo/ui/base/accordion/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "base-alert-dialog": React.lazy(async () => {
    const mod = await import("@/registry/ui/base/alert-dialog/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "base-button": React.lazy(async () => {
    const mod = await import("@/registry/ui/base/button/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "base-checkbox": React.lazy(async () => {
    const mod = await import("@/registry/ui/base/checkbox/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "base-context-menu": React.lazy(async () => {
    const mod = await import("@/registry/ui/base/context-menu/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "base-dialog": React.lazy(async () => {
    const mod = await import("@/registry/ui/base/dialog/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "bottom-sheet": React.lazy(async () => {
    const mod = await import("@/registry/demo/ui/radix/bottom-sheet/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "radix-button": React.lazy(async () => {
    const mod = await import("@/registry/demo/ui/radix/button/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "radix-checkbox": React.lazy(async () => {
    const mod = await import("@/registry/demo/ui/radix/checkbox/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "radix-dialog": React.lazy(async () => {
    const mod = await import("@/registry/demo/ui/radix/dialog/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "primitives-animate-tabs": React.lazy(async () => {
    const mod = await import("@/registry/primitives/animate/tabs/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "primitives-animate-tooltip": React.lazy(async () => {
    const mod = await import("@/registry/primitives/animate/tooltip/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "primitives-buttons-button": React.lazy(async () => {
    const mod = await import("@/registry/primitives/buttons/button/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "primitives-effects-auto-height": React.lazy(async () => {
    const mod = await import(
      "@/registry/primitives/effects/auto-height/index.tsx"
    );
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
  "primitives-radix-tabs": React.lazy(async () => {
    const mod = await import("@/registry/ui/radix/tabs/index.tsx");
    const pascalExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function" && PASCAL_CASE_RE.test(key)
    );
    const functionExportName = Object.keys(mod).find(
      (key) => typeof mod[key] === "function"
    );
    const Comp =
      mod.default ||
      (pascalExportName ? mod[pascalExportName] : undefined) ||
      (functionExportName ? mod[functionExportName] : undefined);
    return { default: Comp };
  }),
};
