/** biome-ignore-all lint: Autogenerated file */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.

export const sourceLoaders: Record<string, () => Promise<any>> = {
  "cursor-trail-reveal": () => import("./sources/cursor-trail-reveal.json"),
  "infinite-scrolling-images": () =>
    import("./sources/infinite-scrolling-images.json"),
  "scroll-chapters": () => import("./sources/scroll-chapters.json"),
  "scroll-gallery": () => import("./sources/scroll-gallery.json"),
  "sticky-scroll-cards": () => import("./sources/sticky-scroll-cards.json"),
  "text-reveal-box": () => import("./sources/text-reveal-box.json"),
  "tilt-slide-transition": () => import("./sources/tilt-slide-transition.json"),
  "hooks-use-auto-height": () => import("./sources/hooks-use-auto-height.json"),
  "hooks-use-controlled-state": () =>
    import("./sources/hooks-use-controlled-state.json"),
  "hooks-use-prefers-reduced-motion": () =>
    import("./sources/hooks-use-prefers-reduced-motion.json"),
  "icons-arrow-right": () => import("./sources/icons-arrow-right.json"),
  "icons-bell": () => import("./sources/icons-bell.json"),
  "icons-chevrons": () => import("./sources/icons-chevrons.json"),
  "icons-copy": () => import("./sources/icons-copy.json"),
  "lib-scroll-trigger-utils": () =>
    import("./sources/lib-scroll-trigger-utils.json"),
  "particle-hover-button": () => import("./sources/particle-hover-button.json"),
  "sliding-chip-button": () => import("./sources/sliding-chip-button.json"),
  "stagger-button": () => import("./sources/stagger-button.json"),
  accordion: () => import("./sources/accordion.json"),
  "expandable-tabs": () => import("./sources/expandable-tabs.json"),
  "inline-testimonials": () => import("./sources/inline-testimonials.json"),
  "cursor-bubble": () => import("./sources/cursor-bubble.json"),
  "hero-carousel": () => import("./sources/hero-carousel.json"),
  highlight: () => import("./sources/highlight.json"),
  "logo-carousel-swapper": () => import("./sources/logo-carousel-swapper.json"),
  "magnetic-cards": () => import("./sources/magnetic-cards.json"),
  "pixel-image-loader": () => import("./sources/pixel-image-loader.json"),
  "progressive-blur": () => import("./sources/progressive-blur.json"),
  skeleton: () => import("./sources/skeleton.json"),
  "skeleton-shimmer": () => import("./sources/skeleton-shimmer.json"),
  "tilt-card": () => import("./sources/tilt-card.json"),
  "video-player": () => import("./sources/video-player.json"),
  "dia-text-reveal": () => import("./sources/dia-text-reveal.json"),
  "draw-underline-link": () => import("./sources/draw-underline-link.json"),
  "fog-text-reveal": () => import("./sources/fog-text-reveal.json"),
  "number-flow": () => import("./sources/number-flow.json"),
  "rolling-text": () => import("./sources/rolling-text.json"),
  "text-cursor-loop": () => import("./sources/text-cursor-loop.json"),
  "text-effect": () => import("./sources/text-effect.json"),
  "text-loop": () => import("./sources/text-loop.json"),
  "text-morph": () => import("./sources/text-morph.json"),
  "text-reveal-block": () => import("./sources/text-reveal-block.json"),
  "text-reveal-mask": () => import("./sources/text-reveal-mask.json"),
  "text-roll": () => import("./sources/text-roll.json"),
  "text-scramble": () => import("./sources/text-scramble.json"),
  typer: () => import("./sources/typer.json"),
  "base-accordion": () => import("./sources/base-accordion.json"),
  "base-alert-dialog": () => import("./sources/base-alert-dialog.json"),
  "base-button": () => import("./sources/base-button.json"),
  "base-checkbox": () => import("./sources/base-checkbox.json"),
  "base-context-menu": () => import("./sources/base-context-menu.json"),
  "base-dialog": () => import("./sources/base-dialog.json"),
  "base-dropdown-menu": () => import("./sources/base-dropdown-menu.json"),
  "base-switch": () => import("./sources/base-switch.json"),
  "base-tooltip": () => import("./sources/base-tooltip.json"),
  "radix-accordion": () => import("./sources/radix-accordion.json"),
  "radix-alert-dialog": () => import("./sources/radix-alert-dialog.json"),
  "radix-button": () => import("./sources/radix-button.json"),
  "radix-checkbox": () => import("./sources/radix-checkbox.json"),
  "radix-context-menu": () => import("./sources/radix-context-menu.json"),
  "radix-dialog": () => import("./sources/radix-dialog.json"),
  "radix-dropdown-menu": () => import("./sources/radix-dropdown-menu.json"),
  "radix-switch": () => import("./sources/radix-switch.json"),
  "radix-tooltip": () => import("./sources/radix-tooltip.json"),
  "demo-cursor-trail-reveal": () =>
    import("./sources/demo-cursor-trail-reveal.json"),
  "demo-infinite-scrolling-images": () =>
    import("./sources/demo-infinite-scrolling-images.json"),
  "demo-scroll-chapters": () => import("./sources/demo-scroll-chapters.json"),
  "demo-scroll-gallery": () => import("./sources/demo-scroll-gallery.json"),
  "demo-sticky-scroll-cards": () =>
    import("./sources/demo-sticky-scroll-cards.json"),
  "demo-text-reveal-box": () => import("./sources/demo-text-reveal-box.json"),
  "demo-tilt-slide-transition": () =>
    import("./sources/demo-tilt-slide-transition.json"),
  "demo-particle-hover-button": () =>
    import("./sources/demo-particle-hover-button.json"),
  "demo-accordion": () => import("./sources/demo-accordion.json"),
  "demo-expandable-tabs": () => import("./sources/demo-expandable-tabs.json"),
  "demo-inline-testimonials": () =>
    import("./sources/demo-inline-testimonials.json"),
  "demo-cursor-bubble": () => import("./sources/demo-cursor-bubble.json"),
  "demo-hero-carousel": () => import("./sources/demo-hero-carousel.json"),
  "demo-highlight": () => import("./sources/demo-highlight.json"),
  "demo-highlight-click": () => import("./sources/demo-highlight-click.json"),
  "demo-logo-carousel-swapper": () =>
    import("./sources/demo-logo-carousel-swapper.json"),
  "demo-magnetic-cards": () => import("./sources/demo-magnetic-cards.json"),
  "demo-progressive-blur": () => import("./sources/demo-progressive-blur.json"),
  "demo-skeleton": () => import("./sources/demo-skeleton.json"),
  "demo-skeleton-shimmer": () => import("./sources/demo-skeleton-shimmer.json"),
  "demo-skeleton-shimmer-basic": () =>
    import("./sources/demo-skeleton-shimmer-basic.json"),
  "demo-tilt-card": () => import("./sources/demo-tilt-card.json"),
  "demo-tilt-card-image": () => import("./sources/demo-tilt-card-image.json"),
  "demo-video-player": () => import("./sources/demo-video-player.json"),
  "demo-dia-text-reveal": () => import("./sources/demo-dia-text-reveal.json"),
  "demo-fog-text-reveal": () => import("./sources/demo-fog-text-reveal.json"),
  "demo-number-flow": () => import("./sources/demo-number-flow.json"),
  "demo-text-cursor-loop": () => import("./sources/demo-text-cursor-loop.json"),
  "demo-text-effect": () => import("./sources/demo-text-effect.json"),
  "demo-text-loop": () => import("./sources/demo-text-loop.json"),
  "demo-text-morph": () => import("./sources/demo-text-morph.json"),
  "demo-text-morph-input": () => import("./sources/demo-text-morph-input.json"),
  "demo-text-reveal-mask": () => import("./sources/demo-text-reveal-mask.json"),
  "demo-text-roll": () => import("./sources/demo-text-roll.json"),
  "demo-typer": () => import("./sources/demo-typer.json"),
  "demo-base-accordion": () => import("./sources/demo-base-accordion.json"),
  "demo-base-accordion-bordered": () =>
    import("./sources/demo-base-accordion-bordered.json"),
  "demo-base-accordion-multiple": () =>
    import("./sources/demo-base-accordion-multiple.json"),
  "demo-base-accordion-separated": () =>
    import("./sources/demo-base-accordion-separated.json"),
  "demo-alert-dialog": () => import("./sources/demo-alert-dialog.json"),
  "demo-alert-dialog-small": () =>
    import("./sources/demo-alert-dialog-small.json"),
  "demo-button": () => import("./sources/demo-button.json"),
  "demo-button-loading": () => import("./sources/demo-button-loading.json"),
  "demo-button-motion": () => import("./sources/demo-button-motion.json"),
  "demo-button-sizes": () => import("./sources/demo-button-sizes.json"),
  "demo-button-variants": () => import("./sources/demo-button-variants.json"),
  "demo-button-with-icon": () => import("./sources/demo-button-with-icon.json"),
  "demo-checkbox": () => import("./sources/demo-checkbox.json"),
  "demo-checkbox-card": () => import("./sources/demo-checkbox-card.json"),
  "demo-checkbox-indeterminate": () =>
    import("./sources/demo-checkbox-indeterminate.json"),
  "demo-checkbox-with-text": () =>
    import("./sources/demo-checkbox-with-text.json"),
  "demo-context-menu": () => import("./sources/demo-context-menu.json"),
  "demo-context-menu-file": () =>
    import("./sources/demo-context-menu-file.json"),
  "demo-context-menu-rtl": () => import("./sources/demo-context-menu-rtl.json"),
  "demo-dialog": () => import("./sources/demo-dialog.json"),
  "demo-dialog-scrollable": () =>
    import("./sources/demo-dialog-scrollable.json"),
  "demo-dialog-share": () => import("./sources/demo-dialog-share.json"),
  "demo-dropdown-menu": () => import("./sources/demo-dropdown-menu.json"),
  "demo-dropdown-menu-rtl": () =>
    import("./sources/demo-dropdown-menu-rtl.json"),
  "demo-switch": () => import("./sources/demo-switch.json"),
  "demo-switch-sizes": () => import("./sources/demo-switch-sizes.json"),
  "demo-switch-with-icon": () => import("./sources/demo-switch-with-icon.json"),
  "demo-base-tooltip": () => import("./sources/demo-base-tooltip.json"),
  "demo-radix-accordion": () => import("./sources/demo-radix-accordion.json"),
  "demo-radix-accordion-bordered": () =>
    import("./sources/demo-radix-accordion-bordered.json"),
  "demo-radix-accordion-multiple": () =>
    import("./sources/demo-radix-accordion-multiple.json"),
  "demo-radix-accordion-separated": () =>
    import("./sources/demo-radix-accordion-separated.json"),
  "demo-radix-alert-dialog": () =>
    import("./sources/demo-radix-alert-dialog.json"),
  "demo-radix-alert-dialog-small": () =>
    import("./sources/demo-radix-alert-dialog-small.json"),
  "demo-radix-button": () => import("./sources/demo-radix-button.json"),
  "demo-radix-button-loading": () =>
    import("./sources/demo-radix-button-loading.json"),
  "demo-radix-button-motion": () =>
    import("./sources/demo-radix-button-motion.json"),
  "demo-radix-button-sizes": () =>
    import("./sources/demo-radix-button-sizes.json"),
  "demo-radix-button-variants": () =>
    import("./sources/demo-radix-button-variants.json"),
  "demo-radix-button-with-icon": () =>
    import("./sources/demo-radix-button-with-icon.json"),
  "demo-radix-checkbox": () => import("./sources/demo-radix-checkbox.json"),
  "demo-radix-checkbox-card": () =>
    import("./sources/demo-radix-checkbox-card.json"),
  "demo-radix-checkbox-indeterminate": () =>
    import("./sources/demo-radix-checkbox-indeterminate.json"),
  "demo-radix-checkbox-with-text": () =>
    import("./sources/demo-radix-checkbox-with-text.json"),
  "demo-radix-context-menu": () =>
    import("./sources/demo-radix-context-menu.json"),
  "demo-radix-context-menu-file": () =>
    import("./sources/demo-radix-context-menu-file.json"),
  "demo-radix-context-menu-rtl": () =>
    import("./sources/demo-radix-context-menu-rtl.json"),
  "demo-radix-dialog": () => import("./sources/demo-radix-dialog.json"),
  "demo-radix-dialog-scrollable": () =>
    import("./sources/demo-radix-dialog-scrollable.json"),
  "demo-radix-dialog-share": () =>
    import("./sources/demo-radix-dialog-share.json"),
  "demo-radix-dropdown-menu": () =>
    import("./sources/demo-radix-dropdown-menu.json"),
  "demo-radix-dropdown-menu-rtl": () =>
    import("./sources/demo-radix-dropdown-menu-rtl.json"),
  "demo-radix-switch": () => import("./sources/demo-radix-switch.json"),
  "demo-radix-switch-sizes": () =>
    import("./sources/demo-radix-switch-sizes.json"),
  "demo-radix-switch-with-icon": () =>
    import("./sources/demo-radix-switch-with-icon.json"),
  "demo-radix-tooltip": () => import("./sources/demo-radix-tooltip.json"),
  "primitives-animate-slot": () =>
    import("./sources/primitives-animate-slot.json"),
  "primitives-animate-tabs": () =>
    import("./sources/primitives-animate-tabs.json"),
  "primitives-animate-tooltip": () =>
    import("./sources/primitives-animate-tooltip.json"),
  "primitives-buttons-button": () =>
    import("./sources/primitives-buttons-button.json"),
  "primitives-effects-auto-height": () =>
    import("./sources/primitives-effects-auto-height.json"),
  "primitives-radix-tabs": () => import("./sources/primitives-radix-tabs.json"),
  "demo-sliding-chip-button": () =>
    import("./sources/demo-sliding-chip-button.json"),
  "demo-stagger-button": () => import("./sources/demo-stagger-button.json"),
  "demo-pixel-image-loader": () =>
    import("./sources/demo-pixel-image-loader.json"),
  "demo-draw-underline-link": () =>
    import("./sources/demo-draw-underline-link.json"),
  "demo-rolling-text": () => import("./sources/demo-rolling-text.json"),
  "demo-text-reveal-block": () =>
    import("./sources/demo-text-reveal-block.json"),
  "demo-text-scramble": () => import("./sources/demo-text-scramble.json"),
  "demo-base-button": () => import("./sources/demo-base-button.json"),
  "demo-base-checkbox": () => import("./sources/demo-base-checkbox.json"),
  "demo-base-switch": () => import("./sources/demo-base-switch.json"),
};

const sourceCache = new Map<string, string>();
const filesCache = new Map<string, any[]>();

export async function loadComponentSource(
  name: string
): Promise<string | null> {
  if (sourceCache.has(name)) {
    return sourceCache.get(name)!;
  }
  const loader = sourceLoaders[name];
  if (!loader) {
    return null;
  }
  try {
    const mod = await loader();
    const data = mod.default || mod;
    const code = data.code || data.files?.[0]?.content || null;
    if (code) {
      sourceCache.set(name, code);
    }
    return code;
  } catch {
    return null;
  }
}

export async function loadComponentFiles(name: string): Promise<any[] | null> {
  if (filesCache.has(name)) {
    return filesCache.get(name)!;
  }
  const loader = sourceLoaders[name];
  if (!loader) {
    return null;
  }
  try {
    const mod = await loader();
    const data = mod.default || mod;
    const files = data.files || null;
    if (files) {
      filesCache.set(name, files);
    }
    return files;
  } catch {
    return null;
  }
}
